<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e9b7c77c-5880-4cf9-b73c-d97f7d4c34a5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.AI.OpenAI" Version="9.4.0-preview.1.25378.8" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="9.7.1-preview.1.25365.4" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="9.7.1" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.61.0" />
    <PackageReference Include="PdfPig" Version="0.1.12-alpha-20250804-bdf3b" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
    <PackageReference Include="Aspire.Qdrant.Client" Version="9.4.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Qdrant" Version="1.61.0-preview" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenaAiLab.ServiceDefaults\GenaAiLab.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
